# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HandsOn_GUI_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 1080)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("HandsOn_Capstone/Glove_Layout_1.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.captureTab = QtWidgets.QWidget()
        self.captureTab.setObjectName("captureTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.captureTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_capFile = QtWidgets.QHBoxLayout()
        self.horizontalLayout_capFile.setObjectName("horizontalLayout_capFile")
        self.labelFile = QtWidgets.QLabel(self.captureTab)
        self.labelFile.setObjectName("labelFile")
        self.horizontalLayout_capFile.addWidget(self.labelFile)
        self.lineEditFileOut = QtWidgets.QLineEdit(self.captureTab)
        self.lineEditFileOut.setObjectName("lineEditFileOut")
        self.horizontalLayout_capFile.addWidget(self.lineEditFileOut)
        self.btnFileOut = QtWidgets.QPushButton(self.captureTab)
        self.btnFileOut.setObjectName("btnFileOut")
        self.horizontalLayout_capFile.addWidget(self.btnFileOut)
        self.verticalLayout_3.addLayout(self.horizontalLayout_capFile)
        self.line = QtWidgets.QFrame(self.captureTab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_gestCap = QtWidgets.QHBoxLayout()
        self.horizontalLayout_gestCap.setObjectName("horizontalLayout_gestCap")
        self.labelGestCap = QtWidgets.QLabel(self.captureTab)
        self.labelGestCap.setObjectName("labelGestCap")
        self.horizontalLayout_gestCap.addWidget(self.labelGestCap)
        self.lineEditGestCap = QtWidgets.QLineEdit(self.captureTab)
        self.lineEditGestCap.setObjectName("lineEditGestCap")
        self.horizontalLayout_gestCap.addWidget(self.lineEditGestCap)
        self.btnGestCap = QtWidgets.QPushButton(self.captureTab)
        self.btnGestCap.setObjectName("btnGestCap")
        self.horizontalLayout_gestCap.addWidget(self.btnGestCap)
        self.verticalLayout_3.addLayout(self.horizontalLayout_gestCap)
        self.labelOutFileViewer = QtWidgets.QLabel(self.captureTab)
        self.labelOutFileViewer.setObjectName("labelOutFileViewer")
        self.verticalLayout_3.addWidget(self.labelOutFileViewer)
        self.plainTextEditFileOut = QtWidgets.QPlainTextEdit(self.captureTab)
        self.plainTextEditFileOut.setObjectName("plainTextEditFileOut")
        self.verticalLayout_3.addWidget(self.plainTextEditFileOut)
        self.tabWidget.addTab(self.captureTab, "")
        self.trainTab = QtWidgets.QWidget()
        self.trainTab.setObjectName("trainTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.trainTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_trainFile = QtWidgets.QHBoxLayout()
        self.horizontalLayout_trainFile.setObjectName("horizontalLayout_trainFile")
        self.labelTrainFile = QtWidgets.QLabel(self.trainTab)
        self.labelTrainFile.setObjectName("labelTrainFile")
        self.horizontalLayout_trainFile.addWidget(self.labelTrainFile)
        self.lineEditTrainFile = QtWidgets.QLineEdit(self.trainTab)
        self.lineEditTrainFile.setObjectName("lineEditTrainFile")
        self.horizontalLayout_trainFile.addWidget(self.lineEditTrainFile)
        self.btnTrainFile = QtWidgets.QPushButton(self.trainTab)
        self.btnTrainFile.setObjectName("btnTrainFile")
        self.horizontalLayout_trainFile.addWidget(self.btnTrainFile)
        self.verticalLayout_4.addLayout(self.horizontalLayout_trainFile)
        self.line_2 = QtWidgets.QFrame(self.trainTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.labelTrainFileViewer = QtWidgets.QLabel(self.trainTab)
        self.labelTrainFileViewer.setObjectName("labelTrainFileViewer")
        self.verticalLayout_4.addWidget(self.labelTrainFileViewer)
        self.plainTextEditTrainFile = QtWidgets.QPlainTextEdit(self.trainTab)
        self.plainTextEditTrainFile.setObjectName("plainTextEditTrainFile")
        self.verticalLayout_4.addWidget(self.plainTextEditTrainFile)
        self.horizontalLayout_train = QtWidgets.QHBoxLayout()
        self.horizontalLayout_train.setObjectName("horizontalLayout_train")
        self.labelTrainStatus = QtWidgets.QLabel(self.trainTab)
        self.labelTrainStatus.setObjectName("labelTrainStatus")
        self.horizontalLayout_train.addWidget(self.labelTrainStatus)
        self.lineEditTrainStatus = QtWidgets.QLineEdit(self.trainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTrainStatus.sizePolicy().hasHeightForWidth())
        self.lineEditTrainStatus.setSizePolicy(sizePolicy)
        self.lineEditTrainStatus.setReadOnly(True)
        self.lineEditTrainStatus.setObjectName("lineEditTrainStatus")
        self.horizontalLayout_train.addWidget(self.lineEditTrainStatus)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_train.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_train.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.trainTab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_train.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_train)
        self.tabWidget.addTab(self.trainTab, "")
        self.classifyRealTab = QtWidgets.QWidget()
        self.classifyRealTab.setObjectName("classifyRealTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.classifyRealTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_ClassRT = QtWidgets.QVBoxLayout()
        self.verticalLayout_ClassRT.setObjectName("verticalLayout_ClassRT")
        self.checkBoxTtoS = QtWidgets.QCheckBox(self.classifyRealTab)
        self.checkBoxTtoS.setObjectName("checkBoxTtoS")
        self.verticalLayout_ClassRT.addWidget(self.checkBoxTtoS)
        self.checkBoxClassRTdebug = QtWidgets.QCheckBox(self.classifyRealTab)
        self.checkBoxClassRTdebug.setObjectName("checkBoxClassRTdebug")
        self.verticalLayout_ClassRT.addWidget(self.checkBoxClassRTdebug)
        self.horizontalLayout_ClassRtDelay = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ClassRtDelay.setObjectName("horizontalLayout_ClassRtDelay")
        self.labelClassRtDelay = QtWidgets.QLabel(self.classifyRealTab)
        self.labelClassRtDelay.setObjectName("labelClassRtDelay")
        self.horizontalLayout_ClassRtDelay.addWidget(self.labelClassRtDelay)
        self.lineEditClassRtDelay = QtWidgets.QLineEdit(self.classifyRealTab)
        self.lineEditClassRtDelay.setObjectName("lineEditClassRtDelay")
        self.horizontalLayout_ClassRtDelay.addWidget(self.lineEditClassRtDelay)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_ClassRtDelay.addItem(spacerItem2)
        self.verticalLayout_ClassRT.addLayout(self.horizontalLayout_ClassRtDelay)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_ClassRT.addItem(spacerItem3)
        self.horizontalLayout_ClassRT = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ClassRT.setObjectName("horizontalLayout_ClassRT")
        self.labelClassRT = QtWidgets.QLabel(self.classifyRealTab)
        self.labelClassRT.setObjectName("labelClassRT")
        self.horizontalLayout_ClassRT.addWidget(self.labelClassRT)
        self.btnClassifyStop = QtWidgets.QPushButton(self.classifyRealTab)
        self.btnClassifyStop.setObjectName("btnClassifyStop")
        self.horizontalLayout_ClassRT.addWidget(self.btnClassifyStop)
        self.btnClassifyStart = QtWidgets.QPushButton(self.classifyRealTab)
        self.btnClassifyStart.setObjectName("btnClassifyStart")
        self.horizontalLayout_ClassRT.addWidget(self.btnClassifyStart)
        self.verticalLayout_ClassRT.addLayout(self.horizontalLayout_ClassRT)
        self.horizontalLayout_4.addLayout(self.verticalLayout_ClassRT)
        self.plainTextEditClassRT = QtWidgets.QPlainTextEdit(self.classifyRealTab)
        self.plainTextEditClassRT.setObjectName("plainTextEditClassRT")
        self.horizontalLayout_4.addWidget(self.plainTextEditClassRT)
        self.plainTextEditClassRT.raise_()
        self.tabWidget.addTab(self.classifyRealTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_dataOut = QtWidgets.QHBoxLayout()
        self.horizontalLayout_dataOut.setObjectName("horizontalLayout_dataOut")
        self.gBoxFlex = QtWidgets.QGroupBox(self.centralwidget)
        self.gBoxFlex.setObjectName("gBoxFlex")
        self.formLayout = QtWidgets.QFormLayout(self.gBoxFlex)
        self.formLayout.setObjectName("formLayout")
        self.indexLabel = QtWidgets.QLabel(self.gBoxFlex)
        self.indexLabel.setObjectName("indexLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.indexLabel)
        self.indexLineEdit = QtWidgets.QLineEdit(self.gBoxFlex)
        self.indexLineEdit.setReadOnly(True)
        self.indexLineEdit.setObjectName("indexLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.indexLineEdit)
        self.indexKnuckleLabel = QtWidgets.QLabel(self.gBoxFlex)
        self.indexKnuckleLabel.setObjectName("indexKnuckleLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.indexKnuckleLabel)
        self.indexKnuckleLineEdit = QtWidgets.QLineEdit(self.gBoxFlex)
        self.indexKnuckleLineEdit.setReadOnly(True)
        self.indexKnuckleLineEdit.setObjectName("indexKnuckleLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.indexKnuckleLineEdit)
        self.middleLabel = QtWidgets.QLabel(self.gBoxFlex)
        self.middleLabel.setObjectName("middleLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.middleLabel)
        self.middleLineEdit = QtWidgets.QLineEdit(self.gBoxFlex)
        self.middleLineEdit.setReadOnly(True)
        self.middleLineEdit.setObjectName("middleLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.middleLineEdit)
        self.middleKnuckleLabel = QtWidgets.QLabel(self.gBoxFlex)
        self.middleKnuckleLabel.setObjectName("middleKnuckleLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.middleKnuckleLabel)
        self.middleKnuckleLineEdit = QtWidgets.QLineEdit(self.gBoxFlex)
        self.middleKnuckleLineEdit.setReadOnly(True)
        self.middleKnuckleLineEdit.setObjectName("middleKnuckleLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.middleKnuckleLineEdit)
        self.ringLabel = QtWidgets.QLabel(self.gBoxFlex)
        self.ringLabel.setObjectName("ringLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ringLabel)
        self.ringLineEdit = QtWidgets.QLineEdit(self.gBoxFlex)
        self.ringLineEdit.setReadOnly(True)
        self.ringLineEdit.setObjectName("ringLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ringLineEdit)
        self.ringKnuckleLabel = QtWidgets.QLabel(self.gBoxFlex)
        self.ringKnuckleLabel.setObjectName("ringKnuckleLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.ringKnuckleLabel)
        self.ringKnuckleLineEdit = QtWidgets.QLineEdit(self.gBoxFlex)
        self.ringKnuckleLineEdit.setReadOnly(True)
        self.ringKnuckleLineEdit.setObjectName("ringKnuckleLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ringKnuckleLineEdit)
        self.pinkyLabel = QtWidgets.QLabel(self.gBoxFlex)
        self.pinkyLabel.setObjectName("pinkyLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pinkyLabel)
        self.pinkyLineEdit = QtWidgets.QLineEdit(self.gBoxFlex)
        self.pinkyLineEdit.setReadOnly(True)
        self.pinkyLineEdit.setObjectName("pinkyLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pinkyLineEdit)
        self.thumbLabel = QtWidgets.QLabel(self.gBoxFlex)
        self.thumbLabel.setObjectName("thumbLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.thumbLabel)
        self.thumbLineEdit = QtWidgets.QLineEdit(self.gBoxFlex)
        self.thumbLineEdit.setReadOnly(True)
        self.thumbLineEdit.setObjectName("thumbLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.thumbLineEdit)
        self.thumbKnuckeLabel = QtWidgets.QLabel(self.gBoxFlex)
        self.thumbKnuckeLabel.setObjectName("thumbKnuckeLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.thumbKnuckeLabel)
        self.thumbKnuckeLineEdit = QtWidgets.QLineEdit(self.gBoxFlex)
        self.thumbKnuckeLineEdit.setReadOnly(True)
        self.thumbKnuckeLineEdit.setObjectName("thumbKnuckeLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.thumbKnuckeLineEdit)
        self.horizontalLayout_dataOut.addWidget(self.gBoxFlex)
        self.gBoxTouch = QtWidgets.QGroupBox(self.centralwidget)
        self.gBoxTouch.setObjectName("gBoxTouch")
        self.formLayout_2 = QtWidgets.QFormLayout(self.gBoxTouch)
        self.formLayout_2.setObjectName("formLayout_2")
        self.indexSideLabel = QtWidgets.QLabel(self.gBoxTouch)
        self.indexSideLabel.setObjectName("indexSideLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.indexSideLabel)
        self.indexSideLineEdit = QtWidgets.QLineEdit(self.gBoxTouch)
        self.indexSideLineEdit.setReadOnly(True)
        self.indexSideLineEdit.setObjectName("indexSideLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.indexSideLineEdit)
        self.indexTopLabel = QtWidgets.QLabel(self.gBoxTouch)
        self.indexTopLabel.setObjectName("indexTopLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.indexTopLabel)
        self.indexTopLineEdit = QtWidgets.QLineEdit(self.gBoxTouch)
        self.indexTopLineEdit.setReadOnly(True)
        self.indexTopLineEdit.setObjectName("indexTopLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.indexTopLineEdit)
        self.middleTopLabel = QtWidgets.QLabel(self.gBoxTouch)
        self.middleTopLabel.setObjectName("middleTopLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.middleTopLabel)
        self.middleTopLineEdit = QtWidgets.QLineEdit(self.gBoxTouch)
        self.middleTopLineEdit.setReadOnly(True)
        self.middleTopLineEdit.setObjectName("middleTopLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.middleTopLineEdit)
        self.middleSideLabel = QtWidgets.QLabel(self.gBoxTouch)
        self.middleSideLabel.setObjectName("middleSideLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.middleSideLabel)
        self.middleSideLineEdit = QtWidgets.QLineEdit(self.gBoxTouch)
        self.middleSideLineEdit.setReadOnly(True)
        self.middleSideLineEdit.setObjectName("middleSideLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.middleSideLineEdit)
        self.ringSideLabel = QtWidgets.QLabel(self.gBoxTouch)
        self.ringSideLabel.setObjectName("ringSideLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ringSideLabel)
        self.ringSideLineEdit = QtWidgets.QLineEdit(self.gBoxTouch)
        self.ringSideLineEdit.setReadOnly(True)
        self.ringSideLineEdit.setObjectName("ringSideLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ringSideLineEdit)
        self.pinkySideLabel = QtWidgets.QLabel(self.gBoxTouch)
        self.pinkySideLabel.setObjectName("pinkySideLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pinkySideLabel)
        self.pinkySideLineEdit = QtWidgets.QLineEdit(self.gBoxTouch)
        self.pinkySideLineEdit.setReadOnly(True)
        self.pinkySideLineEdit.setObjectName("pinkySideLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pinkySideLineEdit)
        self.pinkyTopLabel = QtWidgets.QLabel(self.gBoxTouch)
        self.pinkyTopLabel.setObjectName("pinkyTopLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pinkyTopLabel)
        self.pinkyTopLineEdit = QtWidgets.QLineEdit(self.gBoxTouch)
        self.pinkyTopLineEdit.setReadOnly(True)
        self.pinkyTopLineEdit.setObjectName("pinkyTopLineEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pinkyTopLineEdit)
        self.horizontalLayout_dataOut.addWidget(self.gBoxTouch)
        self.verticalLayout_quat_accel = QtWidgets.QVBoxLayout()
        self.verticalLayout_quat_accel.setObjectName("verticalLayout_quat_accel")
        self.gBoxQuat = QtWidgets.QGroupBox(self.centralwidget)
        self.gBoxQuat.setObjectName("gBoxQuat")
        self.formLayout_3 = QtWidgets.QFormLayout(self.gBoxQuat)
        self.formLayout_3.setObjectName("formLayout_3")
        self.quatWLabel = QtWidgets.QLabel(self.gBoxQuat)
        self.quatWLabel.setObjectName("quatWLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.quatWLabel)
        self.quatWLineEdit = QtWidgets.QLineEdit(self.gBoxQuat)
        self.quatWLineEdit.setReadOnly(True)
        self.quatWLineEdit.setObjectName("quatWLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.quatWLineEdit)
        self.quatXLabel = QtWidgets.QLabel(self.gBoxQuat)
        self.quatXLabel.setObjectName("quatXLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.quatXLabel)
        self.quatXLineEdit = QtWidgets.QLineEdit(self.gBoxQuat)
        self.quatXLineEdit.setReadOnly(True)
        self.quatXLineEdit.setObjectName("quatXLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.quatXLineEdit)
        self.quatYLabel = QtWidgets.QLabel(self.gBoxQuat)
        self.quatYLabel.setObjectName("quatYLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.quatYLabel)
        self.quatYLineEdit = QtWidgets.QLineEdit(self.gBoxQuat)
        self.quatYLineEdit.setReadOnly(True)
        self.quatYLineEdit.setObjectName("quatYLineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.quatYLineEdit)
        self.quatZLabel = QtWidgets.QLabel(self.gBoxQuat)
        self.quatZLabel.setObjectName("quatZLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.quatZLabel)
        self.quatZLineEdit = QtWidgets.QLineEdit(self.gBoxQuat)
        self.quatZLineEdit.setReadOnly(True)
        self.quatZLineEdit.setObjectName("quatZLineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.quatZLineEdit)
        self.verticalLayout_quat_accel.addWidget(self.gBoxQuat)
        self.gBoxAccel = QtWidgets.QGroupBox(self.centralwidget)
        self.gBoxAccel.setObjectName("gBoxAccel")
        self.formLayout_4 = QtWidgets.QFormLayout(self.gBoxAccel)
        self.formLayout_4.setObjectName("formLayout_4")
        self.accelXLabel = QtWidgets.QLabel(self.gBoxAccel)
        self.accelXLabel.setObjectName("accelXLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.accelXLabel)
        self.accelXLineEdit = QtWidgets.QLineEdit(self.gBoxAccel)
        self.accelXLineEdit.setReadOnly(True)
        self.accelXLineEdit.setObjectName("accelXLineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.accelXLineEdit)
        self.accelYLabel = QtWidgets.QLabel(self.gBoxAccel)
        self.accelYLabel.setObjectName("accelYLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.accelYLabel)
        self.accelYLineEdit = QtWidgets.QLineEdit(self.gBoxAccel)
        self.accelYLineEdit.setReadOnly(True)
        self.accelYLineEdit.setObjectName("accelYLineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.accelYLineEdit)
        self.accelZLabel = QtWidgets.QLabel(self.gBoxAccel)
        self.accelZLabel.setObjectName("accelZLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.accelZLabel)
        self.accelZLineEdit = QtWidgets.QLineEdit(self.gBoxAccel)
        self.accelZLineEdit.setReadOnly(True)
        self.accelZLineEdit.setObjectName("accelZLineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.accelZLineEdit)
        self.verticalLayout_quat_accel.addWidget(self.gBoxAccel)
        self.horizontalLayout_dataOut.addLayout(self.verticalLayout_quat_accel)
        self.verticalLayout_adds = QtWidgets.QVBoxLayout()
        self.verticalLayout_adds.setObjectName("verticalLayout_adds")
        self.gBoxSerialParse = QtWidgets.QGroupBox(self.centralwidget)
        self.gBoxSerialParse.setObjectName("gBoxSerialParse")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gBoxSerialParse)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSerialParseStop = QtWidgets.QPushButton(self.gBoxSerialParse)
        self.btnSerialParseStop.setObjectName("btnSerialParseStop")
        self.horizontalLayout.addWidget(self.btnSerialParseStop)
        self.btnSerialParseStart = QtWidgets.QPushButton(self.gBoxSerialParse)
        self.btnSerialParseStart.setObjectName("btnSerialParseStart")
        self.horizontalLayout.addWidget(self.btnSerialParseStart)
        self.verticalLayout_adds.addWidget(self.gBoxSerialParse)
        self.gBoxHandAnimate = QtWidgets.QGroupBox(self.centralwidget)
        self.gBoxHandAnimate.setObjectName("gBoxHandAnimate")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gBoxHandAnimate)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnHandAnimateStop = QtWidgets.QPushButton(self.gBoxHandAnimate)
        self.btnHandAnimateStop.setObjectName("btnHandAnimateStop")
        self.horizontalLayout_3.addWidget(self.btnHandAnimateStop)
        self.btnHandAnimateStart = QtWidgets.QPushButton(self.gBoxHandAnimate)
        self.btnHandAnimateStart.setObjectName("btnHandAnimateStart")
        self.horizontalLayout_3.addWidget(self.btnHandAnimateStart)
        self.verticalLayout_adds.addWidget(self.gBoxHandAnimate)
        self.gBoxPlotSignals = QtWidgets.QGroupBox(self.centralwidget)
        self.gBoxPlotSignals.setObjectName("gBoxPlotSignals")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gBoxPlotSignals)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnPlotSignalsStop = QtWidgets.QPushButton(self.gBoxPlotSignals)
        self.btnPlotSignalsStop.setObjectName("btnPlotSignalsStop")
        self.horizontalLayout_2.addWidget(self.btnPlotSignalsStop)
        self.btnPlotSignalsStart = QtWidgets.QPushButton(self.gBoxPlotSignals)
        self.btnPlotSignalsStart.setObjectName("btnPlotSignalsStart")
        self.horizontalLayout_2.addWidget(self.btnPlotSignalsStart)
        self.verticalLayout_adds.addWidget(self.gBoxPlotSignals)
        self.checkBoxDataOutAvg = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxDataOutAvg.setObjectName("checkBoxDataOutAvg")
        self.verticalLayout_adds.addWidget(self.checkBoxDataOutAvg)
        self.horizontalLayout_dataOut.addLayout(self.verticalLayout_adds)
        self.verticalLayout.addLayout(self.horizontalLayout_dataOut)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HandsOn Developer"))
        self.labelFile.setText(_translate("MainWindow", "Output File:"))
        self.btnFileOut.setText(_translate("MainWindow", "Load/Create File"))
        self.labelGestCap.setText(_translate("MainWindow", "Gesture Identifier:"))
        self.btnGestCap.setText(_translate("MainWindow", "Capture Gesture"))
        self.labelOutFileViewer.setText(_translate("MainWindow", "Output File Viewer:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.captureTab), _translate("MainWindow", "Capture Gesture"))
        self.labelTrainFile.setText(_translate("MainWindow", "Training File:"))
        self.btnTrainFile.setText(_translate("MainWindow", "Load File"))
        self.labelTrainFileViewer.setText(_translate("MainWindow", "Training File Viewer:"))
        self.labelTrainStatus.setText(_translate("MainWindow", "Classifier Status:"))
        self.pushButton.setText(_translate("MainWindow", "Train Classifier"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trainTab), _translate("MainWindow", "Train Classifier"))
        self.checkBoxTtoS.setText(_translate("MainWindow", "Enable Text-to-Speech"))
        self.checkBoxClassRTdebug.setText(_translate("MainWindow", "Enable Debug Output"))
        self.labelClassRtDelay.setText(_translate("MainWindow", "Set Delay (s):"))
        self.labelClassRT.setText(_translate("MainWindow", "Real Time Classification:"))
        self.btnClassifyStop.setText(_translate("MainWindow", "Stop"))
        self.btnClassifyStart.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.classifyRealTab), _translate("MainWindow", "Classify Real Time"))
        self.gBoxFlex.setTitle(_translate("MainWindow", "Flex Sensors"))
        self.indexLabel.setText(_translate("MainWindow", "Index"))
        self.indexKnuckleLabel.setText(_translate("MainWindow", "IndexKnuckle"))
        self.middleLabel.setText(_translate("MainWindow", "Middle"))
        self.middleKnuckleLabel.setText(_translate("MainWindow", "MiddleKnuckle"))
        self.ringLabel.setText(_translate("MainWindow", "Ring"))
        self.ringKnuckleLabel.setText(_translate("MainWindow", "RingKnuckle"))
        self.pinkyLabel.setText(_translate("MainWindow", "Pinky"))
        self.thumbLabel.setText(_translate("MainWindow", "Thumb"))
        self.thumbKnuckeLabel.setText(_translate("MainWindow", "ThumbKnucke"))
        self.gBoxTouch.setTitle(_translate("MainWindow", "Touch Capactive Sensors"))
        self.indexSideLabel.setText(_translate("MainWindow", "IndexSide"))
        self.indexTopLabel.setText(_translate("MainWindow", "IndexTop"))
        self.middleTopLabel.setText(_translate("MainWindow", "MiddleTop"))
        self.middleSideLabel.setText(_translate("MainWindow", "MiddleSide"))
        self.ringSideLabel.setText(_translate("MainWindow", "RingSide"))
        self.pinkySideLabel.setText(_translate("MainWindow", "PinkySide"))
        self.pinkyTopLabel.setText(_translate("MainWindow", "PinkyTop"))
        self.gBoxQuat.setTitle(_translate("MainWindow", "Quaternions"))
        self.quatWLabel.setText(_translate("MainWindow", "quatW"))
        self.quatXLabel.setText(_translate("MainWindow", "quatX"))
        self.quatYLabel.setText(_translate("MainWindow", "quatY"))
        self.quatZLabel.setText(_translate("MainWindow", "quatZ"))
        self.gBoxAccel.setTitle(_translate("MainWindow", "Linear Acceleration"))
        self.accelXLabel.setText(_translate("MainWindow", "accelX"))
        self.accelYLabel.setText(_translate("MainWindow", "accelY"))
        self.accelZLabel.setText(_translate("MainWindow", "accelZ"))
        self.gBoxSerialParse.setTitle(_translate("MainWindow", "Serial Parser"))
        self.btnSerialParseStop.setText(_translate("MainWindow", "Stop"))
        self.btnSerialParseStart.setText(_translate("MainWindow", "Start"))
        self.gBoxHandAnimate.setTitle(_translate("MainWindow", "Hand Animation"))
        self.btnHandAnimateStop.setText(_translate("MainWindow", "Stop"))
        self.btnHandAnimateStart.setText(_translate("MainWindow", "Start"))
        self.gBoxPlotSignals.setTitle(_translate("MainWindow", "Plot Signals"))
        self.btnPlotSignalsStop.setText(_translate("MainWindow", "Stop"))
        self.btnPlotSignalsStart.setText(_translate("MainWindow", "Start"))
        self.checkBoxDataOutAvg.setText(_translate("MainWindow", "Output moving window average"))

